workspace:
  base: /srv/app
  path: src/code.gitea.io/gitea

pipeline:
  test:
    image: webhippie/golang:edge
    pull: true
    environment:
      CGO_ENABLED: 0
      TAGS: cert sqlite pam miniwinsvc
    commands:
      - apk -U add linux-pam-dev openssh-client

      - make clean
      - make vet
#      - make lint fails currently with 500 errors
      - make test
      - make build

  mysql:
    image: webhippie/golang:edge
    pull: true
    commands:
     - make test-mysql
    when:
      event: push

  pgsql:
    image: webhippie/golang:edge
    pull: true
    commands:
     - make test-pgsql
    when:
      event: push

  updater:
    image: karalabe/xgo-latest:latest
    pull: true
    commands:
      - make publish
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

  coverage:
    image: plugins/coverage
    server: https://coverage.gitea.io

  docker1:
    image: plugins/docker
    repo: gitea/gitea
    tags: [ '${TAG}' ]
    when:
      event: tag
      branch: refs/tags/*

  docker2:
    image: plugins/docker
    repo: gitea/gitea
    tags: [ 'latest' ]
    when:
      event: push
      branch: master

  release1:
    image: plugins/s3
    path_style: true
    source: dist/release/
    target: /lgtm/master
    when:
      event: push
      branch: master

  release2:
    image: plugins/s3
    path_style: true
    source: dist/release/
    target: /lgtm/$$TAG
    when:
      event: tag
      branch: refs/tags/*

  release3:
    image: plugins/s3
    path_style: true
    source: dist/latest/
    target: /lgtm/latest
    when:
      event: tag
      branch: refs/tags/*

  github:
    image: plugins/github-release
    files:
      - dist/release/*
    when:
      event: tag
      branch: refs/tags/*

  gitter:
    image: plugins/gitter

services:
  mysqlsvc:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    when:
      event: push

  pgsqlsvc:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=test
    when:
      event: push
