apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3ZA== # rootpasswd
  MYSQL_DATABASE: bXlfZGJfbmFtZQ== # my_db_name
  MYSQL_USER: bXlzcWxfdXNlcg== # mysql_user
  MYSQL_PASSWORD: bXlzcWxfcGFzc3dvcmQ= # mysql_password
