apiVersion: v1
kind: ConfigMap
metadata:
  namespace: go-app-namespace
  name: mariadb-config
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    innodb_file_per_table=1
    max_connections=1000
