apiVersion: v1
kind: Secret
metadata:
  name: go-secrets
type: Opaque
data:
  DB_USERSTORYPROJ_USER: dXNlcnN0b3J5X3VzZXI= # userstory_user
  DB_USERSTORYPROJ_PASSWORD: dXNlcnN0b3J5X3Bhc3N3b3Jk # userstory_password
  DB_USERSTORYPROJ_URL: dXNlcnN0b3J5X3VzZXI6dXNlcnN0b3J5X3Bhc3N3b3JkQHRjcChtYXJpYWRiOjMzMDYpL3VzZXJzdG9yeQ==  # userstory_user:userstory_passwd@tcp(mariadb:3306)/userstory               