apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
  namespace: go-app-namespace
type: Opaque
data:
   DB_USERSTORYPROJ_USER: dXNlcnN0b3J5X3VzZXI= # userstory_user
   DB_USERSTORYPROJ_PASSWORD: dXNlcnN0b3J5X3Bhc3N3b3Jk # userstory_password
   DB_USERSTORYPROJ_URL: dXNlcnN0b3J5X3VzZXI6dXNlcnN0b3J5X3Bhc3N3b3JkQHRjcChtYXJpYWRiOjMzMDYpL3VzZXJzdG9yeQ==  # userstory_user:userstory_passwd@tcp(mariadb:3306)/userstory
   MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3ZA== # rootpasswd
   MYSQL_DATABASE: bXlfZGJfbmFtZQ== # my_db_name
   MYSQL_USER: bXlzcWxfdXNlcg== # mysql_user
   MYSQL_PASSWORD: bXlzcWxfcGFzc3dvcmQ= # mysql_password               

